---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags:
        - docker
    - name: Install Python docker
      pip:
        name: docker-py
        state: present
    - name: Download Docker images
      docker_image:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql:5
        - marios100/project
      tags:
        - docker
    - name: Create Docker network
      docker_network:
        name: myapp_network
        state: present
      tags:
        - docker
    - name: Start MySQL container
      docker_container:
        name: mysql
        image: mysql:5
        published_ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
        networks:
          - name: myapp_network
            #ipv4_address: 172.20.0.2
        state: started
      register: mysql_container
      tags:
        - docker
    - name: Wait for MySQL
      wait_for:
        host: "localhost"
        port: "3306"
        state: started      
    - name: Start web application container
      docker_container:
        name: myapp
        image: martmich/todoappwithlogin:latest
        published_ports:
          - "8080:8080"
        env:
          DB_HOST: mysql
          DB_PORT: 3306
          DB_USER: "{{ db_user }}"
          DB_USER_PASSWORD: "{{ db_user_password }}"
        networks:
          - name: myapp_network
            #ipv4_address: 172.20.0.3
        state: started
        #when: mysql_status_succeeded
        #restart_policy: always
        #depends_on:
        #  - mysql
      tags:
        - docker
#   - name: Connect Docker containers to network
#      docker_network:
#        name: myapp_network
#        #state: connected
#        containers:
#          - mysql
#          - myapp
#      tags:
#        - docker


