---
- name: Deploy application on Azure VM
  hosts: azure_vm
  sudo: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - martmich/todoappwithlogin:latest
        - mysql:5

    - name: Create Docker network
      docker_network:
        name: app_network

    - name: Start MySQL container
      docker_container:
        name: mysql_container
        image: mysql:5
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todos
        networks:
          - name: app_network

    - name: Wait for MySQL to be ready
      wait_for:
        host: "{{ ansible_host }}"
        port: 3306
        delay: 10
        timeout: 120

    - name: Start Web Application container
      docker_container:
        name: webapp_container
        image: martmich/todoappwithlogin:latest
        state: started
        restart_policy: always
        env:
          DB_HOST: mysql_container
          DB_PORT: 3306
          DB_USER: root
          DB_USER_PASSWORD: root
        ports:
          - "8080:8080"
        networks:
          - name: app_network
