---
- name: Deploy application on Azure VM
  hosts: azure_vm
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.docker:
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker images
      ansible.builtin.docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - martmich/todoappwithlogin:latest
        - mysql:5

    - name: Create Docker network
      ansible.builtin.docker_network:
        name: app_network

    - name: Start MySQL container
      ansible.builtin.docker_container:
        name: mysql_container
        image: mysql:5
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todos
        networks:
          - name: app_network

    - name: Wait for MySQL to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 3306
        delay: 10
        timeout: 120

    - name: Start Web Application container
      ansible.builtin.docker_container:
        name: webapp_container
        image: martmich/todoappwithlogin:latest
        state: started
        restart_policy: always
        env:
          DB_HOST: mysql_container
          DB_PORT: 3306
          DB_USER: "{{ db_user }}"
          DB_USER_PASSWORD: "{{ db_user_password }}"
        ports:
          - "8080:8080"
        networks:
          - name: app_network
